// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.25.0
// source: handshake.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// HandshakeServiceClient is the client API for HandshakeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HandshakeServiceClient interface {
	Handshake(ctx context.Context, in *HandshakeRequest, opts ...grpc.CallOption) (*HandshakeResponse, error)
}

type handshakeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHandshakeServiceClient(cc grpc.ClientConnInterface) HandshakeServiceClient {
	return &handshakeServiceClient{cc}
}

func (c *handshakeServiceClient) Handshake(ctx context.Context, in *HandshakeRequest, opts ...grpc.CallOption) (*HandshakeResponse, error) {
	out := new(HandshakeResponse)
	err := c.cc.Invoke(ctx, "/middleware.HandshakeService/Handshake", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HandshakeServiceServer is the server API for HandshakeService service.
// All implementations must embed UnimplementedHandshakeServiceServer
// for forward compatibility
type HandshakeServiceServer interface {
	Handshake(context.Context, *HandshakeRequest) (*HandshakeResponse, error)
	mustEmbedUnimplementedHandshakeServiceServer()
}

// UnimplementedHandshakeServiceServer must be embedded to have forward compatible implementations.
type UnimplementedHandshakeServiceServer struct {
}

func (UnimplementedHandshakeServiceServer) Handshake(context.Context, *HandshakeRequest) (*HandshakeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Handshake not implemented")
}
func (UnimplementedHandshakeServiceServer) mustEmbedUnimplementedHandshakeServiceServer() {}

// UnsafeHandshakeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HandshakeServiceServer will
// result in compilation errors.
type UnsafeHandshakeServiceServer interface {
	mustEmbedUnimplementedHandshakeServiceServer()
}

func RegisterHandshakeServiceServer(s grpc.ServiceRegistrar, srv HandshakeServiceServer) {
	s.RegisterService(&HandshakeService_ServiceDesc, srv)
}

func _HandshakeService_Handshake_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HandshakeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HandshakeServiceServer).Handshake(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/middleware.HandshakeService/Handshake",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HandshakeServiceServer).Handshake(ctx, req.(*HandshakeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HandshakeService_ServiceDesc is the grpc.ServiceDesc for HandshakeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HandshakeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "middleware.HandshakeService",
	HandlerType: (*HandshakeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Handshake",
			Handler:    _HandshakeService_Handshake_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "handshake.proto",
}
